#Database config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/api_alugacasa
    username: root
    password: 1998
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
        #properties:
        #hibernate:
      #dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
spring-doc:
  pathsToMatch: /api/v1/**/**
  swagger-ui:
    use-root-path: true